name = "jiwonz/pathfs"
version = "0.1.0"
description = "luau-path + @lune/fs"
authors = ["jeparlefrancais <jeparlefrancais21@gmail.com>", "jiwonz"]
repository = "https://github.com/jiwonz/lune-path-fs/"
license = "MIT"
includes = ["README.md", "pesde.toml", "init.luau", "types", "luau-path.luau"]

[target]
environment = "lune"
lib = "init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
